# Generated by Django 6.0.2 on 2026-03-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='bill_id',
            field=models.CharField(max_length=100),
        ),
    ]
