# Generated by Django 6.0.2 on 2026-03-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_purchase_bill_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='temp',
            field=models.IntegerField(default=0),
        ),
    ]
