# Generated by Django 6.0.2 on 2026-03-06 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_purchase_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='temp',
        ),
    ]
