# Generated by Django 4.2.29 on 2026-04-03 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_profile_link_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, help_text='Full lesson transcript or notes for PDF download', null=True),
        ),
    ]
