# Generated by Django 4.2.29 on 2026-04-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_coursetimetracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='link_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
